config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  #  devise_for :users
    devise_for :users, path_names: {
                sign_up: '' #Stop Sign Up
        }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

        #root to: "happy_orders#index"
        root to: "happy_customers#index"

        resources :happy_customers do
          resources :happy_quotes, :happy_orders
        end


        resources :happy_quotes do
          resources :happy_quote_lines
          patch :move
          get 'po'
          get 'pwfreight'
          get 'pocreate'
          get 'poview'
          get 'copy'
          get 'createsub'
          get 'sortlines'
        end

        resources :happy_pos do
          resources :happy_po_lines
          get 'finalize'
          get 'poprint'
        end

        #resources :happy_orders do
          #resources :happy_order_lines
        #end

        resources :happy_projects do
          resources :happy_project_tasks
              get 'loadprocess'
          match :add, via: [:get, :post]
        end

        resources :happy_standard_tasks do
           resources :happy_standard_activities
        end

        resources :happy_standard_processes

        resources :happy_reminders do
          collection do
            get :edit_multiple
            put :update_multiple
          end
        end

        resources :happy_project_members
        resources :happy_project_teams

        #resources :happy_standard_tasks
        #resources :happy_standard_processes
        #resources :happy_standard_activities

        resources :happy_vendors

        resources :happy_install_sites do
          get 'customer_select'
        end

        get '/happy_products/productinfo', action: :productinfo,  controller: 'happy_products'
        resources :happy_products
end

app/models/happy_quote.rb
class HappyQuote < ApplicationRecord
  belongs_to :happy_customer
  belongs_to :user
  #has_one :happy_project
  has_many :happy_projects
  has_many :happy_reminders, as: :remindable
  has_many :happy_quote_lines,-> { order(position: :asc) }, inverse_of: :happy_quote
  validates_associated :happy_quote_lines

  accepts_nested_attributes_for :happy_quote_lines, reject_if: :all_blank, allow_destroy: true

  validates :terms,      presence: true
  validates :fob,      presence: true
  validates :quote_date,      presence: true
  validates :estimated_delivery_date,      presence: true
  #validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :shipping_street1,      presence: true
  validates :shipping_city,      presence: true
  validates :shipping_state,      presence: true
  validates :shipping_zipcode,      presence: true

  #validates :name,        presence: true, length: { minimum: 3 }
  #validates :email,       presence: true, format: { with: /.+@.+\.{1}.{2,}/ }
  #validates :password,    length: { within: 8..40 }
  #validates :avatar,      presence: true
  #validates :bio,         length: { within: 100..900 }    
  #validates :birthday,    presence: true, timeliness: { type: :date, :after => lambda { Date.today } }
  #validates :color,       presence: true
  #validates :fruit,       presence: true, exclusion_array: { in: User::FRUIT.first, presence: true, deny_blank: true }
  #validates :music,       presence: true, exclusion_array: { in: User::MUSIC.first, presence: true, deny_blank: true }
  #validates :language,    inclusion: { in: User::LANGUAGE.map(&:to_s) }
  #validates :pill,        inclusion: { in: [User::PILL.first.to_s] }
  #validates :choises,     presence: true, exclusion_array: { in: User::CHOISES.first, presence: true, deny_blank: true }
  #validates :active,      presence: true, acceptance: true
  #validates :friends,     numericality: { only_integer: true, greater_than: 1, less_than: 10_000 }
  #validates :mood,        numericality: { only_integer: true, greater_than: 50, less_than_or_equal_to: 100 } 
  #validates :awake,       presence: true, timeliness: { type: :time, before: '12:00' }
  #validates :first_kiss,  presence: true, timeliness: { type: :datetime, after: '20:00' }
  #validates :terms,       acceptance: true

  
end

app/controllers/happy_quotes_controller.rb
class HappyQuotesController < ApplicationController
before_action :find_quote, only: [:show, :edit, :update, :destroy]
include Reminder

  def index

    @search = params["search"]
    if @search.present?
      puts "got in index"       
        @number = @search["number"]
      puts @number
      #@happyquote = HappyQuote.where("number = ? and happy_customer_id = ?", @number, 13)
      @happyquote = HappyQuote.find_by_id(@number)
      if !@happyquote.nil?
          @cust_id = @happyquote.happy_customer_id
          @happyquote = HappyQuote.where("happy_customer_id = ? and number = ?", @happyquote.happy_customer_id, @number).order("number asc")
          puts "cust_id"
          puts @cust_id
      else 
          flash.now[:alert] = "Quote #{@number} not found!"
      end

    else

    if not current_user.admin? and !@search.present?
        @happyquote = HappyQuote.where("happy_customer_id = ? and user_id = ?", params[:customer_id], current_user.id).order("number desc, sub asc")
     else
        @happyquote = HappyQuote.where("happy_customer_id = ?", params[:customer_id]).order("number desc, sub asc")
     end

     respond_to do |format|
      format.html
      format.json { render json: { happyproduct: @happyproduct } }
    end
  end

  end

  def new
    puts "got in new"       
     @happyquote = HappyQuote.new
     @happyvendors = HappyVendor.all.order("vendor_name asc")
     @happycustomer = HappyCustomer.find(params[:happy_customer_id])
     if params[:shipaddress_same_billaddress]
          @happyquote.shipping_street1 = @happycustomer.mailing_street1
          @happyquote.shipping_street2 = @happycustomer.mailing_street2
          @happyquote.shipping_city = @happycustomer.mailing_city
          @happyquote.shipping_state = @happycustomer.mailing_state
          @happyquote.shipping_zipcode = @happycustomer.mailing_zipcode
     end
     #this is a global variable and was dangerous customers got mixed up
     #$cust_id = @happycustomer.id
  end

  def show

     #helpers.set_model_name
     loadReminder
     #@model_name = controller_name.classify 
     #@happyReminder = HappyReminder.new
     #@happyReminders = HappyReminder.where("remindable_id = ? and remindable_type = ? and user_id = ? and reminder_date >= ?", params[:id], @model_name, current_user.id, Date.today)

     #@happyNotes = HappyNote.where("noteable_id = ? and noteable_type = ?", '1047', 'HappyQuote')
     @quotetotal = HappyQuoteLine.where("happy_quote_id =?",params[:id]).sum('total_line_amount')
     @quoteTaxTotal = HappyQuoteLine.where("happy_quote_id =? and taxable = ?",params[:id],true).sum('total_line_amount')
       @happycustomer=HappyCustomer.find(@happyquote.happy_customer_id)
       @lines = @happyquote.happy_quote_lines
       @pwfreight = HappyQuoteLine.where("happy_quote_id =? and happy_vendor_id = ?",params[:id],'2').count('happy_vendor_id')

       puts "freight"
       puts @pwfreight

     discount_tax_calc

     @happyquote.update_column(:total, @quotetotal)

     respond_to do |format|
      format.html
      format.pdf 
    end
  end


  def simple
     respond_to do |format|
      format.html
      format.pdf 
    end
  end

  def edit
    #@happyquotevendors=HappyQuoteLine.joins(:happy_vendor).where("happy_quote_id =?",params[:happy_quote_id]).distinct.select('happy_vendor_id','happy_vendors.vendor_name', 'first_name') 
     @happyvendors = HappyVendor.select('vendor_name','id').order("vendor_name asc")
     #@happyvendors = HappyVendor.all.order("vendor_name asc")
     #@happycustomer = HappyCustomer.find(@happyquote.happy_customer_id)
     #@filename = "happy_quote.pdf"
     @balance = 0
     @quotetotal = @balance + HappyQuoteLine.where("happy_quote_id =?",params[:id]).sum('total_line_amount')
     #@quotetotal = @balance + HappyQuoteLine.sum('total_line_amount').where("happy_quote_id =?",params[:id])
     #@happyquote = HappyQuote.where("happy_customer_id = ?", params[:customer_id])
    @happyquote = HappyQuote.includes(:happy_customer).includes(:happy_quote_lines).order("happy_quote_lines.position asc").find(params[:id])
     puts "******below happyquote ******"
     puts @happyquote.happy_customer_id
     @happycustomer = HappyCustomer.find(@happyquote.happy_customer_id)
     @useremail = current_user.email
     @quoteTaxTotal = HappyQuoteLine.where("happy_quote_id =? and taxable = ?",params[:id],true).sum('total_line_amount')
     if params[:product_id]
        @happyproduct = HappyProduct.find(params[:product_id])
     end 
     respond_to do |format|
      format.html
      format.pdf
      format.json { render json: { happyproduct: @happyproduct } }
    end

    discount_tax_calc

  end

  #def get_product
   #respond_to do |format|    
      #format.html              
      #format.json { render json: { happyproduct: @happyproduct } } 
    #end
    #puts "here above product"       
   #if params[:productid]
        #@happyproduct = HappyProduct.where("part_number = ?" ,params[:productid])
        ##puts @happyproduct
     #end
  #end

  def create
    #Rails.logger.debug happyquote_params.inspect
    #Rails.logger.debug @happycustomer.inspect

    @happycustomer = HappyCustomer.find(happyquote_params[:happy_customer_id])
    @user = current_user
    
    #@happyquote = @happycustomer.happy_quotes.new(happyquote_params)
    #@happyquote = current_user.happy_customers.happy_quotes.new(happyquote_params)
    # works with happy_customer has many commented out @happyquote = current_user.happy_quotes.new(happyquote_params)
     @happyquote = @happycustomer.happy_quotes.new(happyquote_params)
     @happyquote.user_id = @user.id
    # below works but gives database error look at hidden form fields
     #@happyquote.user=(current_user)
     #@happyquote = @happycustomer.happy_quotes.new(happyquote_params,current_user)
    if @happyquote.save
      flash[:success] = "Quote saved!"
      redirect_to @happyquote
    else
      flash[:alert] = "Quote not saved!"
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      # I had to add below to get vendor select box to work after validation fails
      # render new needs to be there but not sure why below does not execute in new method
      @happyvendors = HappyVendor.all.order("vendor_name asc")
      render :new
    end
  end

  def update
      puts happyquote_params[:fob]
    params[:happy_quote][:happy_quote_lines_attributes].each do |line_number, params|
      puts "here"
      puts line_number
      puts params[:total_line_amount]
      params[:total_line_amount] = params[:total_line_amount].gsub(/[\s,]/ ,"")
    end
    if @happyquote.update(happyquote_params)
       @happyquote.save
      redirect_to @happyquote
    else
      @happycustomer = HappyCustomer.find(happyquote_params[:happy_customer_id])
      @happyvendors = HappyVendor.select('vendor_name','id').order("vendor_name asc")
      render 'edit'
      #render :action => 'edit'
    end
  end

  def remove_commas(num)
    #newnum = (num.replace(/,/g, ''))
    return newnum
  end

  def destroy
    @happyquote.destroy
    redirect_to action: "index"
  end

  def copy
    @happyquote = HappyQuote.includes(:happy_quote_lines).order("happy_quote_lines.position asc").find(params[:happy_quote_id])
    @happyquoteclone = @happyquote.clone   # works for line items
    @happyquotedup = @happyquote.dup   # works for header
    puts "@happyquote number", @happyquote.number
    puts "@happyquoteclone number", @happyquoteclone.number
    puts "@happyquote", @happyquote
    puts "@happyquoteclone", @happyquoteclone
    #@happyquoteclone.sub = @happyquoteclone.sub + 1 

    # Update sub for new header
      @newsub = HappyQuote.where(number: @happyquote.number).count 
      #@happyquotedup.copy = true
     
    # Don't Update original

    # Get id of last header so you can put on details happy_quote_id
    #
    

    @happyquotedup.sub = @newsub
      #@happyquotedup.copy = true
    @happyquotedup.save
    @newid = @happyquotedup.id

      #@headerid=HappyQuote.connection.execute("SELECT currval('happy_quotes_id_seq'::regclass)")

    linePosition = 1

    @happyquoteclone.happy_quote_lines.each { |line|
          @newline = line.dup
          @newline.happy_quote_id = @newid
          @newline.position = linePosition
          #@newline.number = @happyquotedup.number
          #@newline.sub = @happyquotedup.sub
          puts "newline", @newline
          puts "newid", @newid
          puts "in line loop"
          puts line.id
          puts line.product_id
          @newline.save
          linePosition += 1
    }

    flash.notice = "Quote: #{@happyquoteclone.number}-#{@newsub} created." 
    redirect_to action: 'edit', id: @newid
  end


  def createsub
    @happyquote=HappyQuote.find(params[:happy_quote_id])
    @happyquote.number = params[:happy_quote_id]
    @happyquote.sub = @happyquote.sub + 1
    HappyQuote.create    
    #@happyquotelines=HappyQuoteLines.find(params[:happy_quote_id]) do |line|
    #end

    puts "got in createsub"       
  end

  def po
    puts "Po test"
    puts params[:happy_customer_id]
    #@happyproject=HappyProject.where("happy_quote_id = ?", params[:happy_quote_id])
    #@happyproject=HappyProject.find_by("id = ?", 1)
    @happycustomer = HappyCustomer.find(params[:happy_customer_id])
    @happyproject=HappyProject.find_by("happy_quote_id = ?", params[:happy_quote_id])
    @numberLocations=HappyInstallSite.where("happy_customer_id = ?", params[:happy_customer_id]).count
    @happyquotevendors=HappyQuoteLine.joins(:happy_vendor).where("happy_quote_id =?",params[:happy_quote_id]).distinct.select('happy_vendor_id','happy_vendors.vendor_name', 'first_name') 
    #@happyquote = HappyQuote.includes(:happy_customer).includes(:happy_quote_lines).where("happy_vendor_id =?", params[:vendor_id]).order("happy_quote_lines.position asc").find(params[:happy_quote_id])

app/helpers/happy_quotes_helper.rb
module HappyQuotesHelper
end

app/views/happy_quotes/copy.html.erb
<%#= debug @happyquote %>
<%#= debug @happycustomer %>
 <%#= link_to 'Home', root_path %>

<div class="container">
  <h2>Happy Quote - <%= @happyquote.number %></h2>
  <br>
  <div class="row">
    <div class="col-sm-2">
      Customer ID: <%= @happyquote.happy_customer_id %>
    </div>
    <div class="col-sm-3">
      Name: <%= @happyquote.happy_customer.customer_name %>
    </div>
    <div class="col-sm-5">
      Email: <%= @happyquote.email %>
    </div>
    <div class="col-sm-2">
      Newsub: <%= @newsub %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      Copied Quote <%= @happyquote.number %>-<%= @happyquote.sub %> to  <%= @happyquote.number %>-<%= @newsub %>
    </div>
    <div class="col-sm">
    </div>
    <div class="col-sm">
    </div>
    <div class="col-sm">
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <%#= link_to "Yes", happy_quote_createsub_path(:happy_quote_id => @happyquote.id)  %>
    </div>
  </div>
<%#= link_to 'Back', {:action => 'index'} %>
</div>

app/views/happy_quotes/edit.html.erb
<div class="container mb-5">
  <!-- <h2>Edit Quote</h2> -->
  <%= render 'editform' %>
</div>

app/views/happy_quotes/get_product.js.erb
description.innerHTML = '<%= j render "posts/liked-link", post: @post %>';

app/views/happy_quotes/index.html.erb
<%#= debug @happycustomer %>
<%#= debug @happyquote %>
<div class="container">        
    <% if !params[:customer_name] and !@cust_id %>
     <%= simple_form_for :search, url: happy_quotes_path, method: "GET", wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
     <%= f.input_field :number, label: "Quote Number", input_html: {value: ""} %>
     <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
   <% else %>
  <% if params[:customer_name] %>
      <h2>Happy Quotes for - <%= params[:customer_name]%> </h2>
  <% else %>
      <h2>Happy Quote </h2>
  <% end %>
  <br>
  <div class="table-responsive">          
  <table class="table">
    <thead>
      <tr>
        <th>Quote</th>            
        <th>Quote Date</th>          
        <th>Email</th>         
        <th></th>         
        <th></th>         
        <th></th>         
        <th></th>         
        <th></th>         
      </tr>
    </thead>                   
    <tbody>
      <% @happyquote.each do |quote| %>
      <tr>
        <td><%= quote.number %>-<%= quote.sub %></td>     
        <td><%= quote.quote_date %></td>
        <td><%= quote.email %></td>  
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_happy_quote_path(quote) %></td>
        <!-- <td><%#= link_to 'Sortable Quote', happy_quote_sortlines_path(quote,id: quote.id,happy_customer_id: params[:customer_id]) %></td> -->
        <td><%= link_to 'Purchase Orders', happy_quote_po_path(quote, happy_customer_id: params[:customer_id]) %></td>
        <td><%#= link_to 'Destroy', quote, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <% if  params[:customer_id] %>
     <%= link_to 'New Quote', new_happy_quote_path(happy_customer_id: params[:customer_id]) %> 
  <% end %>
<% end %>
</div>

app/views/happy_quotes/new.html.erb
<div class="container mb-5">
  <!-- <h2>Add a New Quote</h2> -->

  <%= render 'newform' %>
</div>

app/views/happy_quotes/pocreate.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <p>

      <% if params[:status] == "draft" %>      
        <h4 class="text-danger">Draft</h4>
      <% else %>
        <h4 class="text-danger">Final</h4>
      <% end %>
      <h3>Purchase Order</h3>
      P.O. #: <%= @happyvendor.id.to_s %>-<%= @happyquote.number.to_s %>-<%= @happyquote.sub.to_s %>
      <br>
      P.O. Date: <%= @happyquote.order_date.strftime("%m-%d-%Y") %>
      </p>
    </div>
    <div class="col-sm-4">
      <%= image_tag "https://d1wfqjcm45bc90.cloudfront.net/happy-erp-logo-v1.png"%>
    </div>
    <div class="col-sm-4 text-danger">
      <p>Certified Woman Owned Small Business<br>
      Native American Owned; TERO certified<br>
      </p>
    </div>
  </div>
  <br>
  <div class="row">            
    <div class="col-sm-4">     
        <p> Happy Playgrounds, LLC<br> 8601 South Oxford Avenue<br> Tulsa, OK 74137
        <br>(918) 851-9518<br> 
        <%= current_user.email %>       
        </p>
    </div>
    <div class="col-sm-4">     
    </div>
    <div class="col-sm-4 text-danger">
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-1">
      VENDOR:
    </div>
    <div class="col-sm-3">
      <p>
      <%= @happyvendor.vendor_name %><br>
      <%= @happyvendor.mailing_street1 %><br>
      <% if @happyvendor.mailing_street2? %>      
        <%= @happyvendor.mailing_street2 %><br>
      <% end %>
      <%= @happyvendor.mailing_city+", "+@happyvendor.mailing_state+" "+@happyvendor.mailing_zipcode %><br>
      <%= @happyvendor.business_phone %>
      </p>
    </div>
    <div class="col-sm-3">
    </div>
    <div class="col-sm-2" align="right">
      <p>SHIP TO:</p> 
    </div>
    <div class="col-sm-3">
      <%= @happyquote.happy_customer.customer_name %><br>
      <%= @happyquote.shipping_street1 %><br>
      <% if @happyquote.shipping_street2? %>
        <%= @happyquote.shipping_street2 %><br>
      <% end %>
      <%= @happyquote.shipping_city %>, <%= @happyquote.shipping_state %> <%= @happyquote.shipping_zipcode %>
    </div>
  </div>
  <br>

<div class="row bg-secondary">
  <div class="col-2 border">
    <b>Part Number</b>
  </div>
  <div class="col-1 border">
    <b>Qty</b>
  </div>
  <div class="col-1 border">
    <b>UOM</b>
  </div>
  <div class="col-3 border">
    <b>Description</b>
  </div>
  <div class="col-1 border">
    <b>Color</b>
  </div>
  <div class="col-2 border">
    <b class="float-right">Unit Price</b>
  </div>
  <div class="col-2 border">
    <b class="float-right">Total</b>
  </div>
</div>

<div>
      <% @lines.each do |quote| %>
        <div data-id="<%= quote.id %>" data-quoteid="<%= quote.id %>" class="card card-body-4">
          <div class="row">
          <div class="col-sm-2">
                <%= quote.product_id %>
          </div>
          <div class="col-sm-1">
                <%= quote.quantity %>
          </div>
          <div class="col-sm-1">
                <%= quote.unit_of_measure %>
          </div>
          <div class="col-sm-3">
                <%= quote.description %>
          </div>
          <div class="col-sm-1">
                <%= quote.color %>
          </div>
          <div class="col-sm-2">
                <div class="float-right">
                  <%= number_to_currency(quote.buyout_unit_price) %>
                </div>
          </div>
          <div class="col-sm-2">
                <div class="float-right">
                  <%= number_to_currency(quote.total_cost_amount) %>
                </div>
          </div>
        </div>
        </div>
      <% end %>
  </div>

  <br><br>
<div class="row">
  <div class="col-8">
    <%#= @happyquote.external_notes %>
    <%= @happyquote.special_instructions %>
  </div>
 <div class="col-2 border">
   <p>
   <b>Sub Total</b><br>
   <b>Tax</b><br>
   <b>Discount</b><br>
   <b>P.O. Amount</b><br>
  </p>
 </div>
 <div class="col-2 border">
   <p class="float-right">
   <%= number_to_currency(@pototal) %><br>
   <%= number_to_currency(@taxAmount) %><br>
   <%= number_to_currency(@discountAmount) %><br>
   <%= number_to_currency(@pototal + @taxAmount - @discountAmount) %>
  </p>
 </div>
 <p><!--<%#= link_to 'Printable P.O. (PDF)', happy_quote_pocreate_path(params[:happy_quote_id], vendor_id:  @happyvendor.id, format: "pdf")%><br> -->
 <%= link_to "Edit Quote", edit_happy_quote_path(@happyquote) %><br>
      <% if params[:status] == "draft" %>      
          <td><%= link_to 'Finalize P.O.', happy_po_finalize_path(params[:happy_quote_id], vendor_id: @happyvendor.id, format: "html")%></td>
        <% else %>
          <%= link_to 'Printable P.O. (PDF)', happy_quote_pocreate_path(params[:happy_quote_id], vendor_id:  @happyvendor.id, format: "pdf")%>
      <% end %>
</div>
</div>

app/views/happy_quotes/projectCreate.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <p>
      <h3>Purchase Order</h3>
      P.O. #: <%= @happyvendor.id.to_s %>-<%= @happyquote.id.to_s %>
      <br>
      P.O. Date: <%= @happyquote.order_date.strftime("%m-%d-%Y") %>
      </p>
    </div>
    <div class="col-sm-4">
      <%= image_tag "https://d1wfqjcm45bc90.cloudfront.net/happy-erp-logo-v1.png"%>
    </div>
    <div class="col-sm-4 text-danger">
      <p>Certified Woman Owned Small Business<br>
      Native American Owned; TERO certified<br>
      </p>
    </div>
  </div>
  <br>
  <div class="row">            
    <div class="col-sm-4">     
        <p> Happy Playgrounds, LLC<br> 8601 South Oxford Avenue<br> Tulsa, OK 74137
        <br>(918) 851-9518<br> 
        <%= current_user.email %>       
        </p>
    </div>
    <div class="col-sm-4">     
    </div>
    <div class="col-sm-4 text-danger">
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-1">
      VENDOR:
    </div>
    <div class="col-sm-3">
      <p>
      <%= @happyvendor.vendor_name %><br>
      <%= @happyvendor.mailing_street1 %><br>
      <% if @happyvendor.mailing_street2? %>      
        <%= @happyvendor.mailing_street2 %><br>
      <% end %>
      <%= @happyvendor.mailing_city+", "+@happyvendor.mailing_state+" "+@happyvendor.mailing_zipcode %><br>
      <%= @happyvendor.business_phone %>
      </p>
    </div>
    <div class="col-sm-3">
    </div>
    <div class="col-sm-2" align="right">
      <p>SHIP TO:</p> 
    </div>
    <div class="col-sm-3">
      <%= @happyquote.happy_customer.customer_name %><br>
      <%= @happyquote.shipping_street1 %><br>
      <% if @happyquote.shipping_street2? %>
        <%= @happyquote.shipping_street2 %><br>
      <% end %>
      <%= @happyquote.shipping_city %>, <%= @happyquote.shipping_state %> <%= @happyquote.shipping_zipcode %>
    </div>
  </div>
  <br>

<div class="row bg-secondary">
  <div class="col-2 border">
    <b>Part Number</b>
  </div>
  <div class="col-1 border">
    <b>Qty</b>
  </div>
  <div class="col-1 border">
    <b>UOM</b>
  </div>
  <div class="col-3 border">
    <b>Description</b>
  </div>
  <div class="col-1 border">
    <b>Color</b>
  </div>
  <div class="col-2 border">
    <b class="float-right">Unit Price</b>
  </div>
  <div class="col-2 border">
    <b class="float-right">Total</b>
  </div>
</div>

<div>
      <% @lines.each do |quote| %>
        <div data-id="<%= quote.id %>" data-quoteid="<%= quote.id %>" class="card card-body-4">
          <div class="row">
          <div class="col-sm-2">
                <%= quote.product_id %>
          </div>
          <div class="col-sm-1">
                <%= quote.quantity %>
          </div>
          <div class="col-sm-1">
                <%= quote.unit_of_measure %>
          </div>
          <div class="col-sm-3">
                <%= quote.description %>
          </div>
          <div class="col-sm-1">
                <%= quote.color %>
          </div>
          <div class="col-sm-2">
                <div class="float-right">
                  <%= number_to_currency(quote.buyout_unit_price) %>
                </div>
          </div>
          <div class="col-sm-2">
                <div class="float-right">
                  <%= number_to_currency(quote.total_cost_amount) %>
                </div>
          </div>
        </div>
        </div>
      <% end %>
  </div>

  <br><br>
<div class="row">
  <div class="col-8">
    <%= @happyquote.external_notes %>
  </div>
 <div class="col-2 border">
   <p>
   <b>Sub Total</b><br>
   <b>Tax</b><br>
   <b>Discount</b><br>
   <b>P.O. Amount</b><br>
  </p>
 </div>
 <div class="col-2 border">
   <p class="float-right">
   <%= number_to_currency(@pototal) %><br>
   <%= number_to_currency(@taxAmount) %><br>
   <%= number_to_currency(@discountAmount) %><br>
   <%= number_to_currency(@pototal + @taxAmount - @discountAmount) %>
  </p>
 </div>
 <p><%= link_to 'Printable P.O. (PDF)', happy_quote_pocreate_path(params[:happy_quote_id], vendor_id:  @happyvendor.id, format: "pdf")%><br>
 <%= link_to "Edit Quote", edit_happy_quote_path(@happyquote) %></p>
</div>
</div>