config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  #  devise_for :users
    devise_for :users, path_names: {
                sign_up: '' #Stop Sign Up
        }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

        #root to: "happy_orders#index"
        root to: "happy_customers#index"

        resources :happy_customers do
          resources :happy_quotes, :happy_orders
        end


        resources :happy_quotes do
          resources :happy_quote_lines
          patch :move
          get 'po'
          get 'pwfreight'
          get 'pocreate'
          get 'poview'
          get 'copy'
          get 'createsub'
          get 'sortlines'
        end

        resources :happy_pos do
          resources :happy_po_lines
          get 'finalize'
          get 'poprint'
        end

        #resources :happy_orders do
          #resources :happy_order_lines
        #end

        resources :happy_projects do
          resources :happy_project_tasks
              get 'loadprocess'
          match :add, via: [:get, :post]
        end

        resources :happy_standard_tasks do
           resources :happy_standard_activities
        end

        resources :happy_standard_processes

        resources :happy_reminders do
          collection do
            get :edit_multiple
            put :update_multiple
          end
        end

        resources :happy_project_members
        resources :happy_project_teams

        #resources :happy_standard_tasks
        #resources :happy_standard_processes
        #resources :happy_standard_activities

        resources :happy_vendors

        resources :happy_install_sites do
          get 'customer_select'
        end

        get '/happy_products/productinfo', action: :productinfo,  controller: 'happy_products'
        resources :happy_products
end

app/controllers/happy_standard_processes_controller.rb
class HappyStandardProcessesController < ApplicationController
  before_action :find_process, only: [:show, :edit, :update, :destroy]
#  before_action :set_happy_standard_process, only: [:show, :edit, :update, :destroy]
#  before_action :set_happy_process, only: [:show, :edit, :update, :destroy]

  def index
    @happyStandardProcesses = HappyStandardProcess.order("process_name ASC").page params[:page]
    @search = params["search"]
    if @search.present?
      @name = @search["process_name"]
      @happyStandardProcesses = HappyStandardProcess.where("process_name ILIKE ?", "%#{@name}%").order("process_name DESC").page(params[:page])
    end
  end

  #def index
    #@happyProcesses = current_user.happy_processes
    #@happyStandardProcesses = HappyStandardProcess.page params[:page]
  #end

  # GET /processes/1
  # GET /processes/1.json
  def show
    @happyStandardProcess.user_id = current_user.id
  end

  # GET /processes/new
  def new
    @happyStandardProcess = HappyStandardProcess.new
  end

  # GET /happy_processes/1/edit
  def edit
  end

  # POST /happy_processes
  # POST /happy_processes.json
  def create
    #@user = current_user
    @happyStandardProcess = HappyStandardProcess.new(happyStandardProcess_params)
    @happyStandardProcess.user_id = current_user.id

    respond_to do |format|
      if @happyStandardProcess.save
        format.html { redirect_to @happyStandardProcess, notice: 'Process was successfully created.' }
        format.json { render :show, status: :created, location: @happyStandardProcess }
      else
        format.html { render :new }
        format.json { render json: @happyStandardProcess.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /happy_processes/1
  # PATCH/PUT /happy_processes/1.json
  def update
    @happyStandardProcess.user_id = current_user.id
    respond_to do |format|
      if @happyStandardProcess.update(happyUpdateStandardProcess_params)
        format.html { redirect_to @happyStandardProcess, notice: 'Process was successfully updated.' }
        format.json { render :show, status: :ok, location: @happyStandardProcess }
      else
        format.html { render :edit }
        format.json { render json: @happyStandardProcess.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /happy_processes/1
  # DELETE /happy_processes/1.json
  def destroy
    @happyStandardProcess.destroy
    respond_to do |format|
      format.html { redirect_to happy_processes_url, notice: 'Process was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def happyStandardProcess_params
      params.require(:happy_standard_process).permit!
    end

    def happyUpdateStandardProcess_params
      params.require(:hp).permit!
    end

    def find_process
      @happyStandardProcess = HappyStandardProcess.find(params[:id])
    end

    #def set_happy_standard_task
      #@happyStandardProcess = HappyStandardProcess.find(params[:id])
    #end

    #def set_happy_task_task
      #@happyStandardProcess = @happyStandardProcess.find(params[:id])
    #end

    # Only allow a list of trusted parameters through.
    #def task_params
      #params.require(:task).permit(:name, :description)
    #end
end

app/views/happy_standard_processes/_new_form.html.erb
<div class="container mb-5">
  <h2>Happy Standard Project Processes</h2>
  <br>

  <%#= link_to 'Home', root_path %>

<%= simple_form_for @happyStandardProcess,
  wrapper: :vertical_form,
  wrapper_mappings: {
    boolean:       :vertical_boolean,
    check_boxes:   :vertical_collection,
    date:          :vertical_multi_select,
    datetime:      :vertical_multi_select,
    file:          :vertical_file,
    radio_buttons: :vertical_collection,
    range:         :vertical_range,
    time:          :vertical_multi_select
  } do |f| %>

  <%= f.error_notification %>

  <%= f.input :process_name %>

  <div class="form-group row">
    <div class="col-4">
        <%= f.input :description %>
    </div>

    <div class="col-3">
        <%#= f.input :process_type, label: false, placeholder: "Process Type"%>
        <%= f.input :process_type, collection: [['Playground','Playground'], ['Shade','Shade'], ['Shelter','Shelter'], ['Surfacing','Surfacing'], ['Purchasing','Purchasing'] ] %>
    </div>

    <div class="col-4">
        <%= f.input :status %>
    </div>

  </div>


  <div class="form-group row mb-0">
    <div class="col-sm-9">
      <%= f.button :submit, class: "btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>
</div>

app/views/happy_standard_processes/index.html.erb
<%#= debug(params) %>
<%#= params[:project_id] %>
<div class="container">


  <h2>Happy Standard Project Processes</h2>
  
  <div class="customer-index-form">
     <%= simple_form_for :search, url: happy_standard_processes_path, method: "GET", html: { class: 'form-inline' } do |f| %>
     <label>
        <%= f.input :process_name, input_html: {value: ""} %>
     </label>

     <label>
        <%= f.submit "Search", class: "btn btn-primary" %>
     </label>
     <% end %>
  </div>

  <%= page_entries_info @happyStandardProcesses %>
  <div class="table-responsive">          
  <table class="table">
    <thead>
      <tr>
        <th>Process ID</th>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @happyStandardProcesses.each do |standardProcess| %>
      <tr>
        <td><%= standardProcess.id %></td>
        <td><%= standardProcess.process_name %></td>
        <td><%= standardProcess.description %></td>
        <% if params[:project_id] %> 
          <td><%=link_to "Add Process - #{params[:project_name]}", happy_project_loadprocess_path(happy_project_id:  params[:project_id], id: standardProcess.id) %></td>
          <td></td>
        <% else %>
        <td><%= link_to 'Show', standardProcess %></td>
        <td><%= link_to 'Add Standard Task', happy_standard_tasks_path%></td>
        <td><%#= link_to 'Edit', edit_happy_customer_path(customer) %></td>
        <td><%#= link_to 'Destroy', customer, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
        <td><%#= link_to 'Quotes', happy_quotes_path(customer_id: customer.id, customer_name: customer.customer_name) %></td>
        <td><%#= link_to 'Orders', happy_orders_path %></td>
        <td><%#= link_to 'Vendors', happy_vendors_path %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <%= paginate @happyStandardProcesses, window: 2 %>
<%= link_to 'New Process', new_happy_standard_process_path, class: 'btn btn-primary'%>
<%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
</div>

app/views/happy_standard_processes/new.html.erb
<!-- <h2>Create Customer</h2> -->
<%= render 'new_form' %>

app/views/happy_standard_processes/show.html.erb
<div class="container">
  <!-- <%#= link_to 'Home', root_path %> -->
  <h2>Happy Standard Project Process - <%= @happyStandardProcess.process_name %></h2>
  <br>
  <div class="row">
    <div class="col-sm">
      <p>
      <%= @happyStandardProcess.description %><br>
      </p>
    </div>
  </div>


  <div class="mb-4">
    <h6>Select below tasks</h6><br>
      <%= form_for(@happyStandardProcess) do |f| %>
        <div class="field">
          <%= hidden_field_tag "hp[happy_standard_task_ids][]" %>
          <% HappyStandardTask.all.each do |task| %>
            <%= check_box_tag "hp[happy_standard_task_ids][]", task.id, @happyStandardProcess.happy_standard_task_ids.include?(task.id) %>
            <%= task.task_name %>
          <% end %>
          </div>
          <%= f.hidden_field :user_id, :as => :hidden, :input_html => { :value => @happyStandardProcess.user_id} %>
             <br>
            <%= f.submit class: 'btn btn-primary' %>
            <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
        </div>
      <% end %>

<%#= link_to 'Back', {:action => 'index'} %>
</div>