config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  #  devise_for :users
    devise_for :users, path_names: {
                sign_up: '' #Stop Sign Up
        }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

        #root to: "happy_orders#index"
        root to: "happy_customers#index"

        resources :happy_customers do
          resources :happy_quotes, :happy_orders
        end


        resources :happy_quotes do
          resources :happy_quote_lines
          patch :move
          get 'po'
          get 'pwfreight'
          get 'pocreate'
          get 'poview'
          get 'copy'
          get 'createsub'
          get 'sortlines'
        end

        resources :happy_pos do
          resources :happy_po_lines
          get 'finalize'
          get 'poprint'
        end

        #resources :happy_orders do
          #resources :happy_order_lines
        #end

        resources :happy_projects do
          resources :happy_project_tasks
              get 'loadprocess'
          match :add, via: [:get, :post]
        end

        resources :happy_standard_tasks do
           resources :happy_standard_activities
        end

        resources :happy_standard_processes

        resources :happy_reminders do
          collection do
            get :edit_multiple
            put :update_multiple
          end
        end

        resources :happy_project_members
        resources :happy_project_teams

        #resources :happy_standard_tasks
        #resources :happy_standard_processes
        #resources :happy_standard_activities

        resources :happy_vendors

        resources :happy_install_sites do
          get 'customer_select'
        end

        get '/happy_products/productinfo', action: :productinfo,  controller: 'happy_products'
        resources :happy_products
end

app/models/happy_project.rb
class HappyProject < ApplicationRecord
#  belongs_to :happy_quote
  has_many :happy_project_tasks, inverse_of: :happy_project
  accepts_nested_attributes_for :happy_project_tasks, reject_if: :all_blank, allow_destroy: true
  has_many :happy_project_teams
  has_many :happy_project_members, through: :happy_project_teams
  has_many :happy_reminders, as: :remindable
  #belongs_to :user
  #has_many :happy_project_members, :through => :happy_project_teams

  #after_save :new_project_steps

  validates :project_name,      presence: true

  validate :verify_project_name_uniqueness, on: :create

#validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def verify_project_name_uniqueness
    errors.add(:base, 'Project Name is already in use') if HappyProject.where(project_name: project_name).exists?
  end

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def status
    return 'in-progress' if self.status = 'in-progress'
    return 'not-started' if happy_project_tasks.none?

    if happy_project_tasks.all? { |task| task.complete? }
      'complete'
    elsif happy_project_tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    puts happy_project_tasks.none
    return 0 if happy_project_tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    happy_project_tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    happy_project_tasks.count
  end

  
  def new_project_steps
    project_id = self.id
    user_id = self.user_id
    puts "project_id"
    puts project_id
    puts "user_id"
    puts user_id
    @happyProjectMember = HappyProjectMember.where("user_id = ?", user_id).first
    #puts @happyProjectMember.first_name
    if HappyProjectMember.where("user_id = ?", user_id).exists?
        puts "exists"
        happyProjectTeam = HappyProjectTeam.create(happy_project_member_id: @happyProjectMember.id, happy_project_id: project_id, team_name: self.project_name, user_id: user_id, status: 'created')
    else
        puts "does not exist"
        happyUser = User.find(user_id)

        intial_name = happyUser.email.split('@')
        name = intial_name[0].split('.')
        first_name = name[0]
        last_name = name[1]

        happyProjectMember = HappyProjectMember.create(first_name: first_name, last_name: last_name, email: happyUser.email, user_id: user_id)

        #happyProjectMemberID = HappyProjectMember.where("user_id = ?", user_id)

        #puts "memberid"

        #puts happyProjectMemberID.id

        #happyProjectTeam = HappyProjectTeam.create(happy_project_member_id: happyProjectMemberID.id, happy_project_id: project_id, team_name: self.project_name, user_id: user_id, status: 'created')

        puts "below creates"
        #happyProjectMember = HappyProjectMember.new

    end
  end
end

app/controllers/happy_projects_controller.rb
class HappyProjectsController < ApplicationController
  before_action :set_happy_project, only: [:show, :edit, :update, :destroy, :add]

  # GET /happy_projects
  # GET /happy_projects.json
  def index
    #@happyprojects = current_user.happy_projects
    @happyProjects = HappyProject.page params[:page]
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

    @model_name = controller_name.classify
     #helpers.set_model_name
     puts "Model"
     puts @model_name

     @happyReminder = HappyReminder.new
     @happyReminders = HappyReminder.where("remindable_id = ? and remindable_type = ? and user_id = ? and reminder_date >= ?", params[:id], @model_name, current_user.id, Date.today)

    @happyProjectTask = @happyProject.happy_project_tasks.new
    @happyProjectMembersCount = @happyProject.happy_project_members.distinct.count()

    #association = HappyNote.reflect_on_all_associations(:belongs_to).first
    #polymorphic = association.options[:polymorphic]

    #associations = ApplicationRecord.subclasses.select do |model|
    #    model.reflect_on_all_associations(:has_many).any? do |has_many_association|
    #        has_many_association.options[:as] == association.name
    #  end
    #end
    #@model_name = controller_name.classify
    puts "model"
    puts @model_name
    #puts "association"
    #puts association
    #puts "polymorphic"
    #puts polymorphic
    #puts "associations"
    #puts associations
    #puts "testReflect"
    #puts $testReflect
  end

  # GET /projects/new
  def new
    @happyProject = HappyProject.new
    @happyvendors = HappyVendor.all.order("vendor_name asc")
      @happyCustomer = HappyCustomer.find(params[:happy_customer_id])
      @happyQuote = HappyQuote.find(params[:happy_quote_id])
      @happyInstallSite = HappyInstallSite.find(params[:happy_install_site_id])

    #@happyProject.name = @happyInstallSite.name
    @happyProject.description = @happyInstallSite.description
    @happyProject.site_contact_phone = @happyInstallSite.phone
    @happyProject.site_contact_email = @happyInstallSite.email
    @happyProject.actual_start_date = Date.today
    @happyProject.planned_budget = @happyQuote.total
    

    @user = current_user
    user_id = @user.id
    if HappyProjectMember.where("user_id = ?", user_id).exists?
      puts "exists"
    else
      puts "does not exist"
      happyUser = User.find(user_id)

      intial_name = happyUser.email.split('@')
      name = intial_name[0].split('.')
      first_name = name[0]
      last_name = name[1]

      happyProjectMember = HappyProjectMember.create(first_name: first_name, last_name: last_name, email: happyUser.email, user_id: user_id)
    end
  end


  # GET /happy_projects/1/edit
  def edit
    puts "got in edit"
    @happyvendors = HappyVendor.select('vendor_name','id').order("vendor_name asc")
    @happyProject = HappyProject.includes(:happy_project_tasks).order("happy_project_tasks.position asc").find(params[:id])
  end

  # POST /happy_projects
  # POST /happy_projects.json
  def create
    puts "create params"
    puts params
    
    @happyProject = HappyProject.new(happyProject_params)
    #params[:happy_quote_id] = @happyProject.happy_quote_id

    puts "after params"
    puts params
    @user = current_user
    @happyProject.user_id = @user.id
    @happyProject.status = 'in-progress'
    #@happyProject.happy_quote_id = @happy_quote_id
    #@happyProject.happy_quote_id = "1008"
  

    respond_to do |format|
      if @happyProject.save
        format.html { redirect_to @happyProject, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @happyProject }
      else
        @happyQuote = HappyQuote.find(happyProject_params[:happy_quote_id])
        @happyCustomer = HappyCustomer.find(happyProject_params[:happy_customer_id])
        @happyInstallSite = HappyInstallSite.find(happyProject_params[:happy_install_site_id])
        @happyvendors = HappyVendor.all.order("vendor_name asc")
        format.html { render :new }
        format.json { render json: @happyProject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /happy_projects/1
  # PATCH/PUT /happy_projects/1.json
  def update
     #raise params.inspect
    puts "got in update"
    #@happyProject.happy_quote_id = 1062
    
    if params[:addjoin] # addjoin is a name on the submit button
    respond_to do |format|
      #if params[:happyProject_params]
          #form_params = happyProject_params
      #else
          #form_params =happyUpdateProject_params
      #end
      #if @happyProject.update(happyProject_params)
         #@happyProject.save!
      if @happyProject.update(happyUpdateProject_params)
        format.html { redirect_to @happyProject, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @happyProject }
      else
        @happyvendors = HappyVendor.select('vendor_name','id').order("vendor_name asc")
        format.html { render :edit }
        format.json { render json: @happyProject.errors, status: :unprocessable_entity }
      end
    end
  else
    respond_to do |format|
      #if params[:happyProject_params]
          #form_params = happyProject_params
      #else
          #form_params =happyUpdateProject_params
      #end
      #if @happyProject.update(happyProject_params)
         #@happyProject.save!
      if @happyProject.update(happyProject_params)
        format.html { redirect_to @happyProject, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @happyProject }
      else
        format.html { render :edit }
        format.json { render json: @happyProject.errors, status: :unprocessable_entity }
      end
    end

  end
  

  end

  def add 
    puts "got in add"

    @happyMembers = HappyProjectMember.where("happy_vendor_id is null and happy_customer_id is null")

    @happyProjectVendors = HappyQuoteLine.joins(:happy_vendor).where("happy_quote_id = ? and happy_vendor_id is not null", params[:happy_quote_id]).distinct.select('happy_vendor_id', 'happy_vendors.vendor_name')
    
    if @happyProjectVendors.exists?
      @happyProjectVendors.each do |projectVendor|
          #@happyVendorMembers = HappyProjectMember.where("happy_vendor_id = ?", "#{projectVendor.happy_vendor_id}").distinct
          @happyVendorMembers = HappyProjectMember.where("happy_vendor_id = ?", "#{projectVendor.happy_vendor_id}").distinct
       end
    end
   
    @happyProjectCustomer = HappyQuote.joins(:happy_customer).where("happy_quotes.id = ?", params[:happy_quote_id]).select('happy_customers.id', 'happy_customers.customer_name')

    #@happyProjectCustomer = HappyCustomer.where("id =?", 9)

    #@happyCustomerMember = HappyProjectMember.all
    if @happyProjectCustomer.exists?
      @happyProjectCustomer.each do |projectCustomer|
        @happyCustomerMember = HappyProjectMember.where("happy_customer_id = ?", "#{projectCustomer.id}")
     end
          #@happyCustomerMember = HappyProjectMember.where("happy_customer_id = ?", @happyProjectCustomer.id) 
    end
    
    #@happyProject.happy_quote_id = 1062
    #respond_to do |format|
      #if params[:happyProject_params]
          #form_params = happyProject_params
      #else
          #form_params =happyUpdateProject_params
      #end
      #if @happyProject.update(happyProject_params)
         #@happyProject.save!
         #if request.post?
          #@course = Course.find(params[:course_id])
          #@student.student_course_assignments << @course
      #end
      #if @happyProject.update(happyProject_params)
        #format.html { redirect_to @happyProject, notice: 'Project was successfully updated.' }
        #format.json { render :show, status: :ok, location: @happyProject }
     # else
        #format.html { render :edit }
       # format.json { render json: @happyProject.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /happy_projects/1
  # DELETE /happy_projects/1.json
  def destroy
    @happyProject.destroy
    respond_to do |format|
      format.html { redirect_to happy_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def loadprocess
    happyProcess = HappyStandardProcess.find(params[:id])
    task_ids = Array.new()
    task_ids = happyProcess.happy_standard_task_ids
    puts "Task ids"
    puts task_ids

    happyTasks = HappyStandardTask.where(id: task_ids)
    puts "happyTasks"
    puts happyTasks
    Rails.logger.debug happyTasks.inspect
    #@happyTasks = @happyProcess.happy_standard_tasks.includes(:happy_standard_activities)
    # p = HappyStandardTask.find(1).happy_standard_activities
    #Rails.logger.debug @happyTasks.inspect

    #@happyActivities = @happyActivities.ties)
    #@happyTasksClone = @happyTasks.clone
    #
    @user = current_user
    
    happyTasks.each { |task|
                            #happyActivities = HappyStandardActivity.where(happy_standard_task_id: task.id)
                                 #happyActivities.each { |activity|
                                        #puts "top activity"
                                        #puts activity.activity_name
                                        #puts "below activity"
                                 #}
                            puts task.id
                            puts task.task_name
                            puts task.description
                            happyProjectTask = HappyProjectTask.create(happy_project_id: params[:happy_project_id],happy_vendor_id: task.happy_vendor_id, 
                              task_name: task.task_name, 
                              description: task.description,
                              priority: task.priority, 
                              dependency: task.dependency, 
                              lead_time: task.lead_time, 

app/views/happy_projects/add.html.erb
<%#= debug(@happyProject) %>
<%#= debug(@happyProjectCustomer) %>
<div class="container">
  <!-- <%#= link_to 'Home', root_path %> -->
  <h2>Happy Project Team - <%= @happyProject.project_name %></h2>
  <br>
  <!-- 
  <div class="row">
    <div class="col-sm">
      <p>
      <%#= @happyStandardProcess.description %><br>
      </p>
    </div>
  
  </div>
  -->


  <div class="mb-2">
    <h4>Happy Employees</h4>
      <%= form_for(@happyProject) do |f| %>
        <div class="field">
          <%= hidden_field_tag "ht[happy_project_member_ids][]" %>
          
          <div class="ml-4">
          <% @happyMembers.each do |member| %>
           
          <%= check_box_tag "ht[happy_project_member_ids][]", member.id, @happyProject.happy_project_member_ids.include?(member.id) %>
          <%= link_to "#{member.first_name} #{member.last_name}", edit_happy_project_member_path(id: member.id, happy_project_id: params[:happy_project_id]) %>, <%= member.title%>, <%= member.role%>
              <br>
            
          <% end %>
           <br>
        </div>          

 <% if @happyProjectVendors.exists? %>  
    <h4>Happy Vendors</h4>
    <% @happyProjectVendors.each do |projectVendor| %>
        <td><%= projectVendor.happy_vendor_id %></td>
        <td>-<%= projectVendor.vendor_name %> - </td>
         <%= link_to "Add new #{projectVendor.vendor_name} member", new_happy_project_member_path(happy_vendor_id: projectVendor.happy_vendor_id, vendor_name: projectVendor.vendor_name, happy_project_id: params[:happy_project_id]) %><br><br>
        <div class="ml-4">

         <%# HappyProjectMember.customer('9').each do |member| %>
        <% #@happyVendorMembers.each do |member| %>
           <% HappyProjectMember.vendor(projectVendor.happy_vendor_id).each do |member| %>
          <%= check_box_tag "ht[happy_project_member_ids][]", member.id, @happyProject.happy_project_member_ids.include?(member.id) %>
          
          <%= link_to "#{member.first_name} #{member.last_name}", edit_happy_project_member_path(id: member.id, happy_project_id: params[:happy_project_id]) %>, <%= member.title%>, <%= member.role%>
              <br>
          <br>
           
        <% end %>
        <br>
        </div>
    <% end%>
   <% end %>

          <h4>Happy Customer</h4>
          <% @happyProjectCustomer.each do |projectCustomer| %>
              <td><%= projectCustomer.id %></td>
              <td>-<%= projectCustomer.customer_name %> - </td>
              <%= link_to "Add new #{projectCustomer.customer_name} member", new_happy_project_member_path(happy_customer_id: projectCustomer.id, customer_name: projectCustomer.customer_name, happy_project_id: params[:happy_project_id]) %><br><br>
                  <div class="ml-4">
                  <% @happyCustomerMember.each do |member| %>
                  
                      <%= check_box_tag "ht[happy_project_member_ids][]", member.id, @happyProject.happy_project_member_ids.include?(member.id) %>
          <%= link_to "#{member.first_name} #{member.last_name}", edit_happy_project_member_path(id: member.id, happy_project_id: params[:happy_project_id]) %>, <%= member.title%>, <%= member.role%>
                    
                  <% end %>
                  <br>
                  </div>
          <% end %>
        </div>
            <%= f.submit class: 'btn btn-primary', :name => "addjoin" %>
            <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
        <% end %>
  </div>
      
<!-- 
<%# @happyVendorMembers.each do |vendorMember| %>
        <td><%#= vendorMember.first_name %></td>
        <td><%#= vendorMember.last_name %> - </td>
<%# end %>


  <%# if @happyProjectVendors.exists? %>  
    <h1>Vendors</h1>
    <%# @happyProjectVendors.each do |projectVendor| %>
        <% #@happyVendorMembers.each do |vendorMember| %>
          <td><%#= projectVendor.happy_vendor_id %></td>
          <td><%#= projectVendor.vendor_name %> - </td>
          <%# if projectVendor.happy_vendor_id = vendorMember.happy_vendor_id %>
             <%#= link_to 'Add big boy', happy_project_member_path(happy_vendor_id: projectVendor.happy_vendor_id, vendor_name: projectVendor.vendor_name, happy_project_id: params[:happy_project_id]) %><br>
             <#%= link_to 'View/Add Team Members', happy_project_team_path(id: '40', happy_project_id: params[:happy_project_id], happy_vendor_id: params[:happy_vendor_id] ), class: 'btn btn-light' %>
             <% #break %>
          <%# else %>
            <%#= link_to 'Add', new_happy_project_member_path(happy_vendor_id: projectVendor.happy_vendor_id, vendor_name: projectVendor.vendor_name, happy_project_id: params[:happy_project_id]) %><br>
          <br>
           <% #end %>
        <% #end %>
    <% #end%>
   <% #end %>
   <% #if @happyProjectCustomer.exists? %> 
    <h1>Customers</h1>
   <%# @happyProjectCustomer.each do |projectCustomer| %>
      <td><%#= projectCustomer.id %></td>
      <td><%#= projectCustomer.customer_name %> - </td>
       <%#= link_to 'Add', new_happy_project_member_path(customer_id: projectCustomer.id, customer_name: projectCustomer.customer_name, happy_project_id: params[:happy_project_id]) %><br>
      <br>
    <%# end%>
  <#% end %>
<%#= link_to 'New Happy Team Member', new_happy_project_member_path %><br>
<%#= link_to 'New Happy Vendor Member', new_happy_project_member_path %><br>
-->

<%#= link_to 'Back', {:action => 'show'} %>
</div>

app/views/happy_projects/edit.html.erb
<!-- <h2>Create project</h2> -->
<%= render 'edit_form' %>

app/views/happy_projects/edit_happy_members.html.erb
<div class="container">
  <!-- <%#= link_to 'Home', root_path %> -->
  <h2>Happy Team members - <%= @happyProject.project_name %></h2>
  <br>
  <div class="row">
    <div class="col-sm">
      <p>
      <%= @happyProject.description %><br>
      </p>
    </div>
  </div>


  <div class="mb-4">
    <h6>Select from the below members</h6><br>
      <%= form_for(@happyProject) do |f| %>
        <div class="field">
          <%#= hidden_field_tag "ht[happy_project_member_ids][]" %>
          <% User.all.each do |member| %>
            <%#= check_box_tag "ht[happy_project_member_ids][]", member.id, @happyProject.happy_project_member_ids.include?(task.id) %>
            <%#= task.task_name %>
             <%= member.email %>
          <% end %>
          </div>
          <%#= f.hidden_field :user_id, :as => :hidden, :input_html => { :value => @happyStandardProcess.user_id} %>
             <br>
            <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>

<%= link_to 'Back', {:action => 'index'} %>
</div>

app/views/happy_projects/index.html.erb
<div class="container">
  <div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <h2>Happy  Projects</h2>
      <%#= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
    </h2>

    <% @happyProjects.each do |project| %>

      <%= link_to project, class: 'text-decoration-none' do %>
        <div class="card project-card mb-3">

          <div class="card-body">
            <div class="mb-3">
              <span class="badge badge-<%#= project.badge_color %>">
                <%#= project.status %>
              </span>
              <span class='text-secondary'>
                <medium>
                  <%= project.percent_complete %>% complete
                  (<%= project.total_complete %>/<%= project.total_tasks %> tasks)
                </medium>
              </span>
            </div>
            <h5 class='card-title text-dark'><b>Project: </b><%= project.project_name %></h5>
            <p class='text-secondary'>
            
            <b>Description: </b><%= project.description %> <b>Planned start date: </b><%= project.planned_start_date %>
            
            </p>
          </div> <!-- margin bottom 3 inner card  -->
          
          

        </div>  <!-- top margin bottom 3  -->

        <!--
          <div class="card mb-3">
             <div class="card-body">
               <div class="row mb-3">
                  <div class='col text-secondary'>
                    <b>Description: </b><%#= project.description %> <b>Planned start date: </b><%#= project.planned_start_date %>
                  </div>
                  <div class="col text-secondary">
                    <b>Description: </b><%#= project.description %> <b>Planned start date: </b><%#= project.planned_start_date %>
                  </div>
                </div>
             </div>
          </div>

        -->

      <% end %> <!-- link to -->
      
    <% end %> <!-- happy project do -->
  
  </div> <!-- top card body -->

</div> <!-- top card -->


</div> <!-- container -->

app/views/happy_projects/show.html.erb
<%#= debug @happyProject %>
<div class="container">
  <!-- <%#= link_to 'Home', root_path %> -->
  <h2>Happy Project - <%= @happyProject.project_name %></h2>
  <br>
  <div class="row">
    <div class="col-sm">
      <!--<p>
      <%#= @happyProject.project_name %><br>
      </p> -->
      <% if @happyProjectMembersCount %>
      <p>
     
      <%= link_to 'View Team Members', happy_project_add_path(id: @happyProject.id,happy_project_id: @happyProject.id, happy_quote_id: @happyProject.happy_quote_id, happy_customer_id: @happyProject.happy_customer_id), class: 'btn btn-light' %>
      <%#= link_to 'View/Add Team Members', happy_project_members_path(happy_project_id: @happyProject.id, happy_quote_id: @happyProject.happy_quote_id ), class: 'btn btn-light' %>
      <%#= link_to 'View/Add Team Members', happy_project_team_path(happy_project_id: @happyProject.id, happy_quote_id: @happyProject.happy_quote_id ), class: 'btn btn-light' %>
         - (<%= @happyProjectMembersCount %>)<br>
      </p>
      <% else %>
      <p>
      <%= link_to 'Create Project Team', new_happy_project_members_path(happy_project_id: @happyProject.id, happy_quote_id: @happyProject.happy_quote_id ), class: 'btn btn-light' %>
        <!--  - (<%= @happyProjectMembersCount %>)<br> -->
      </p>
      <% end %>
    </div>
  </div>


<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <div class="mb-3">
              <span class="badge badge-<%= @happyProject.badge_color %>">
                <%= @happyProject.status %>
              </span>
              <span class='text-secondary'>
                <small>
                  <!--
                  <%#= @happyProject.percent_complete %>% complete
                  (<%#= @happyProject.total_complete %>/<%#= @happyProject.total_tasks %> tasks)
                  -->
                </small>
              </span>
      </div>

      <span><%#= @happyProject.project_name %></span>
      <div>
        <%= link_to 'Edit', edit_happy_project_path(@happyProject), class: 'btn btn-light' %>
        <%= link_to 'Destroy', @happyProject, method: :delete, class: 'btn btn-dark', data: { confirm: 'Are you sure?' } %>
      </div>
    </h2>

    <div class="mb-4">
      <h6><%= link_to "Add Happy Standard Process", happy_standard_processes_path(:project_id => @happyProject.id, :project_name => @happyProject.project_name), class: 'btn btn-light' %> </h6>
      
      <%= form_for([@happyProjectTask.happy_project, @happyProjectTask]) do |f| %>
        <% if @happyProjectTask.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@happyProjectTask.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
            <% @happyProjectTask.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.hidden_field :status, value: 'not-started' %>
        <div class="input-group">
          <%= f.text_field :description, class: 'form-control', placeholder: 'Enter task description...', required: true %>
          <div class="input-group-append">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>


    <h4>Tasks</h4>
    <% @happyProject.happy_project_tasks.each do |task| %>
      <% if task.persisted? %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <span class="badge badge-<%= task.badge_color %> mb-3"><%= task.status %></span>
              <div>
                <%= link_to 'Edit', edit_happy_project_path(@happyProject), class: 'btn btn-light' %>
                <%#= link_to 'Edit', edit_happy_project_happy_project_task_path(task.happy_project, task), class: 'btn btn-light btn-sm' %>
                <%= link_to 'Destroy', [task.happy_project, task], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-dark btn-sm' %>
              </div>
            </div>
            <h5 class='card-title mb-2'>
              <span><%= task.task_name %></span>
            </h5>
            <p><%= task.description %></p>
          </div>
        </div>
      <% end %>
    <% end%>

  </div>
</div>



  <div class="row">
    <div class="col-9">
        <%= link_to 'Back', happy_projects_path, class: 'btn btn-secondary mb-3' %>
    </div>
    <div class="col-3">
      <%#= link_to 'Add Reminder', new_happy_note_path(project_id: @happyProject.id), class: 'btn btn-light' %>
      <!-- Button trigger modal 
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Create Project Reminder
</button> -->
</div>
  </div>