config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  #  devise_for :users
    devise_for :users, path_names: {
                sign_up: '' #Stop Sign Up
        }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

        #root to: "happy_orders#index"
        root to: "happy_customers#index"

        resources :happy_customers do
          resources :happy_quotes, :happy_orders
        end


        resources :happy_quotes do
          resources :happy_quote_lines
          patch :move
          get 'po'
          get 'pwfreight'
          get 'pocreate'
          get 'poview'
          get 'copy'
          get 'createsub'
          get 'sortlines'
        end

        resources :happy_pos do
          resources :happy_po_lines
          get 'finalize'
          get 'poprint'
        end

        #resources :happy_orders do
          #resources :happy_order_lines
        #end

        resources :happy_projects do
          resources :happy_project_tasks
              get 'loadprocess'
          match :add, via: [:get, :post]
        end

        resources :happy_standard_tasks do
           resources :happy_standard_activities
        end

        resources :happy_standard_processes

        resources :happy_reminders do
          collection do
            get :edit_multiple
            put :update_multiple
          end
        end

        resources :happy_project_members
        resources :happy_project_teams

        #resources :happy_standard_tasks
        #resources :happy_standard_processes
        #resources :happy_standard_activities

        resources :happy_vendors

        resources :happy_install_sites do
          get 'customer_select'
        end

        get '/happy_products/productinfo', action: :productinfo,  controller: 'happy_products'
        resources :happy_products
end

app/models/happy_project.rb
class HappyProject < ApplicationRecord
#  belongs_to :happy_quote
  has_many :happy_project_tasks, inverse_of: :happy_project
  accepts_nested_attributes_for :happy_project_tasks, reject_if: :all_blank, allow_destroy: true
  has_many :happy_project_teams
  has_many :happy_project_members, through: :happy_project_teams
  has_many :happy_reminders, as: :remindable
  #belongs_to :user
  #has_many :happy_project_members, :through => :happy_project_teams

  #after_save :new_project_steps

  validates :project_name,      presence: true

  validate :verify_project_name_uniqueness, on: :create

#validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def verify_project_name_uniqueness
    errors.add(:base, 'Project Name is already in use') if HappyProject.where(project_name: project_name).exists?
  end

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def status
    return 'in-progress' if self.status = 'in-progress'
    return 'not-started' if happy_project_tasks.none?

    if happy_project_tasks.all? { |task| task.complete? }
      'complete'
    elsif happy_project_tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    puts happy_project_tasks.none
    return 0 if happy_project_tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    happy_project_tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    happy_project_tasks.count
  end

  
  def new_project_steps
    project_id = self.id
    user_id = self.user_id
    puts "project_id"
    puts project_id
    puts "user_id"
    puts user_id
    @happyProjectMember = HappyProjectMember.where("user_id = ?", user_id).first
    #puts @happyProjectMember.first_name
    if HappyProjectMember.where("user_id = ?", user_id).exists?
        puts "exists"
        happyProjectTeam = HappyProjectTeam.create(happy_project_member_id: @happyProjectMember.id, happy_project_id: project_id, team_name: self.project_name, user_id: user_id, status: 'created')
    else
        puts "does not exist"
        happyUser = User.find(user_id)

        intial_name = happyUser.email.split('@')
        name = intial_name[0].split('.')
        first_name = name[0]
        last_name = name[1]

        happyProjectMember = HappyProjectMember.create(first_name: first_name, last_name: last_name, email: happyUser.email, user_id: user_id)

        #happyProjectMemberID = HappyProjectMember.where("user_id = ?", user_id)

        #puts "memberid"

        #puts happyProjectMemberID.id

        #happyProjectTeam = HappyProjectTeam.create(happy_project_member_id: happyProjectMemberID.id, happy_project_id: project_id, team_name: self.project_name, user_id: user_id, status: 'created')

        puts "below creates"
        #happyProjectMember = HappyProjectMember.new

    end
  end
end

app/models/happy_project_member.rb
class HappyProjectMember < ApplicationRecord
  has_many :happy_project_teams
  #has_many :happy_projects, :through => :happy_project_teams
  has_many :happy_projects, through: :happy_project_teams
  #belongs_to :users
  attr_accessor :happy_project_id
  scope :vendor, ->(vendor_id) { where("happy_vendor_id = ?", vendor_id) }
  scope :customer, ->(customer_id) { where("happy_customer_id = ?", customer_id) }

end

app/controllers/happy_project_members_controller.rb
class HappyProjectMembersController < ApplicationController
  before_action :set_happy_project_member, only: [:show, :edit, :update, :destroy]

  # GET /happy_projects
  # GET /happy_projects.json
  def index
    #@happyprojects = current_user.happy_projects
    @happyProject = HappyProject.find(params[:happy_project_id])
    #@happyProjectMembers = happHappyProjectMember.page params[:page]
    # last working 7/4 @happyProjectMembers = HappyProjectMember.find(happyProject.happy_project_member_ids) 
    #@happyProjectMembers = HappyProjectMember.find(happyProject.happy_project_member_ids).where("happy_vendor_id =?", '2')
    #if params[:happy_venodor_id].nil?
      if (params.has_key?(:happy_vendor_id))
         @happyProjectMembers = HappyProjectMember.where("happy_vendor_id =?", params[:happy_vendor_id])
         #@happyProjectMembers = HappyProjectMember.find(happyProject.happy_project_member_ids)
         puts "top params"
    else
      #@happyProjectMembers = HappyProjectMember.where("happy_vendor_id =?", '2')   
      @happyProjectMembers = HappyProjectMember.find(@happyProject.happy_project_member_ids)
         puts "bottom params"
    end
   
    @happyProjectVendors = HappyQuoteLine.joins(:happy_vendor).where("happy_quote_id = ? and happy_vendor_id is not null", params[:happy_quote_id]).distinct.select('happy_vendor_id', 'happy_vendors.vendor_name')
    @happyUsers = User.joins(:happy_project_members).where.not(users: :current_user)
    #@happyCustomer = HappyCustomer.find(params[:happy_customer_id])
    @happyProjectCustomer = HappyQuote.joins(:happy_customer).where("happy_quotes.id = ?", params[:happy_quote_id]).select('happy_customers.id', 'happy_customers.customer_name')
    
     if @happyProjectVendors.exists?  
      @happyProjectVendors.each do |projectVendor| 
          
          @happyVendorMembers = HappyProjectMember.where("happy_vendor_id = ?", "#{projectVendor.happy_vendor_id}").distinct
       end
      end 
    
    
    #@happyVendorMembers = HappyProjectMember.where(happy_vendor_id = @happyProjectVendors.happy_vendor_ids)
    #@happyCustomerMembers = HappyProjectMember.find(happyProject.happy_project_member_ids)

    #happyProjectTeam = HappyProjectTeam.create(happy_project_id: params[:happy_project_id], happy_project_member_id: 15)
    @search = params["search"]
    if @search.present?
      @lastName = @search["last_name"]
      @happyProjectMembers = HappyProjectMember.where("last_name ILIKE ?", "%#{@lastName}%").order("last_name DESC").page(params[:page])
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    #@happyProjectTask = @happyProject.happy_project_tasks.new
  end

  # GET /projects/new
  def new
    @happyProjectMember = HappyProjectMember.new
  end

  # GET /happy_projects/1/edit
  def edit
    puts "got in edit"
    @happyProjectMember = HappyProjectMember.find(params[:id])
  end

  # POST /happy_projects
  # POST /happy_projects.json
  def create
    #puts params
    #puts params[:happy_quote_id]
    puts "HappyProject"
    puts params[:happy_project_id]
    puts "HappyVendor"
    puts params[:happy_vendor_id]
    @happyProjectMember = HappyProjectMember.new(happyprojectmember_params)
    happyProject = HappyProject.find(@happyProjectMember.happy_project_id)
    @user = current_user
    @happyProjectMember.user_id = @user.id
    
    #@happyProjectMember.happy_quote_id = 1062
   #@happyProject.happy_project_members.create(@happHappyProjectMember) 
    
    respond_to do |format|
      #if @happyProjectMember.save
       if happyProject.happy_project_members << @happyProjectMember
        format.html { redirect_to happyProject, notice: 'Project Member was successfully created.' }
        format.json { render :show, status: :created, location: @happyProjectMember }
      else
        format.html { render :new }
        format.json { render json: @happyProjectMember.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /happy_projects/1
  # PATCH/PUT /happy_projects/1.json
  def update
    happyProject = HappyProject.find(happyprojectmember_params[:happy_project_id])
    respond_to do |format|
      if @happyProjectMember.update(happyprojectmember_params)
         @happyProjectMember.save
        format.html { redirect_to happyProject, notice: 'Project Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @happyProjectMember }
      else
        format.html { render :edit }
        format.json { render json: @happyProjectMember.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /happy_projects/1
  # DELETE /happy_projects/1.json
  def destroy
    @happyProjectMember.destroy
    respond_to do |format|
      format.html { redirect_to happy_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #def loadprocess
    #happyProcess = HappyStandardProcess.find(params[:id])
    #task_ids = Array.new()
    #task_ids = happyProcess.happy_standard_task_ids
    #puts task_ids
#
    #happyTasks = HappyStandardTask.where(id: task_ids)
    #puts happyTasks
    #Rails.logger.debug happyTasks.inspect
    #@happyTasks = @happyProcess.happy_standard_tasks.includes(:happy_standard_activities)
    # p = HappyStandardTask.find(1).happy_standard_activities
    #Rails.logger.debug @happyTasks.inspect

    #@happyActivities = @happyActivities.ties)
    #@happyTasksClone = @happyTasks.clone
    #

    #happyTasks.each { |task|
                            #happyActivities = HappyStandardActivity.where(happy_standard_task_id: task.id)
                                 #happyActivities.each { |activity|
                                        #puts "top activity"
                                        #puts activity.activity_name
                                        #puts "below activity"
                                 #}
                            ##puts task.id
                            #puts task.task_name
                            #puts task.description
                            #}
    #puts @happyTasks
    ##@happyStandardProcess = HappyProcessFlow.includes(:happy_quote_lines).order("happy_quote_lines.id asc").find(params[:happy_quote_id])
    #puts "got in loadProcess"
  #end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_happy_project_member
      @happyProjectMember = HappyProjectMember.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def happyprojectmember_params
      params.require(:happy_project_member).permit(:first_name, :last_name, :title, :role, :state, :email, :phone_number, :is_sms, :is_muted, :happy_project_id)
      
      #params.require(:happy_project).permit(:id, :project_name, :description, :general_contractor,
                     #:site_contact_name, :site_contact_phone, :site_contact_email,
                     #:planned_start_date, :planned_budget, :internal_notes, :external_notes,
                     #:reminder_date, :is_reminder, :status, happy_project_tasks_attributes: [:id, :happy_project_id,
                      #:happy_vendor_id,        
                      #:task_name,        
                      #:description,          
                      #:sales_order,          
                      #:planned_start_date,          
                      #:planned_end_date,          
                      #:actual_start_date,          
                      #:actual_end_date,          
                      #:order_date,          
                      #:ship_date,          
                      #:estimated_delivery_date,          
                      #:receipt_date,          
                      #:reminder_date,          
                      #:priority,             
                      #:group,                
                      #:dependency,
                      #:lead_time,
                      #:is_vendor,            
                      #:duration,                      
                      #:duration_unit,        
                      #:internal_notes,        
                      #:external_notes,        
                      #:is_vendor,            
                      #:_destroy])  
    end
end

app/views/happy_project_members/_edit_form.html.erb
<%#= debug(params) %>
<div class="container mb-5">
   <% if (params.has_key?(:happy_vendor_id)) %>
      <h2>Happy Project Member for <%= params[:vendor_name] %></h2>
    <% elseif (params.has_key?(:happy_vendor_id))%>
      <h2>Happy Project Member for <%= params[:customer_name] %></h2>
    <% else %>
      <h2>Happy Member </h2>
   <% end %>
  <br>

  <%#= link_to 'Home', root_path %>

<%= simple_form_for @happyProjectMember,
  wrapper: :vertical_form,
  wrapper_mappings: {
    boolean:       :vertical_boolean,
    check_boxes:   :vertical_collection,
    date:          :vertical_multi_select,
    datetime:      :vertical_multi_select,
    file:          :vertical_file,
    radio_buttons: :vertical_collection,
    range:         :vertical_range,
    time:          :vertical_multi_select
  } do |f| %>

  <%= f.error_notification %>


  <div class="form-group row">
    <div class="col-4">
        <%= f.input :first_name, label: false, placeholder: "First Name" %>
    </div>

    <div class="col-4">
        <%= f.input :last_name, label: false, placeholder: "Last Name"%>
    </div>

    <div class="col-4">
        <%= f.input :title, label: false, placeholder: "Title" %>
    </div>
  </div>

   <div class="form-group row">
    <div class="col-4">
        <%= f.input :role, label: false, placeholder: "Role" %>
    </div>

    <div class="col-4">
        <%= f.input :email, label: false, placeholder: "Email"%>
    </div>

    <div class="col-4">
        <%= f.input :phone_number, label: false, placeholder: "Phone Number" %>
    </div>
  </div>

   <div class="form-group row">
    <div class="col-4">
        <%= f.input :is_muted, label: "Mute" %>
    </div>
  </div>

   

  <%= f.input :happy_customer_id, :as => :hidden, :input_html => { :value => params[:happy_customer_id]} %>
  <%= f.input :happy_vendor_id, :as => :hidden, :input_html => { :value => params[:happy_vendor_id]} %>
  <%= f.input :happy_project_id, :as => :hidden, :input_html => { :value => params[:happy_project_id]} %>
  <%#= f.hidden_field :happy_project_id, :as => :hidden, :input_html => { :value => params[:happy_project_id]} %>


  <div class="form-group row mb-0">
    <div class="col-sm-9">
      <%= f.button :submit, class: "btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>
</div>

app/views/happy_project_members/_new_form.html.erb
<%#= debug(params) %>
<div class="container mb-5">
   <% if (params.has_key?(:happy_vendor_id)) %>
    <h2>Happy Project Member for <%= params[:vendor_name] %></h2>
    <% else %>
    <h2>Happy Project Member for <%= params[:customer_name] %></h2>
   <% end %>
  <br>

  <%#= link_to 'Home', root_path %>

<%= simple_form_for @happyProjectMember,
  wrapper: :vertical_form,
  wrapper_mappings: {
    boolean:       :vertical_boolean,
    check_boxes:   :vertical_collection,
    date:          :vertical_multi_select,
    datetime:      :vertical_multi_select,
    file:          :vertical_file,
    radio_buttons: :vertical_collection,
    range:         :vertical_range,
    time:          :vertical_multi_select
  } do |f| %>

  <%= f.error_notification %>


  <div class="form-group row">
    <div class="col-4">
        <%= f.input :first_name, label: false, placeholder: "First Name" %>
    </div>

    <div class="col-4">
        <%= f.input :last_name, label: false, placeholder: "Last Name"%>
    </div>

    <div class="col-4">
        <%= f.input :title, label: false, placeholder: "Title" %>
    </div>
  </div>

   <div class="form-group row">
    <div class="col-4">
        <%= f.input :role, label: false, placeholder: "Role" %>
    </div>

    <div class="col-4">
        <%= f.input :email, label: false, placeholder: "Email"%>
    </div>

    <div class="col-4">
        <%= f.input :phone_number, label: false, placeholder: "Phone Number" %>
    </div>
  </div>

   <div class="form-group row">
    <div class="col-4">
        <%= f.input :is_muted, label: "Mute" %>
    </div>
  </div>

   

  <%= f.input :happy_customer_id, :as => :hidden, :input_html => { :value => params[:happy_customer_id]} %>
  <%= f.input :happy_vendor_id, :as => :hidden, :input_html => { :value => params[:happy_vendor_id]} %>
  <%= f.input :happy_project_id, :as => :hidden, :input_html => { :value => params[:happy_project_id]} %>
  <%#= f.hidden_field :happy_project_id, :as => :hidden, :input_html => { :value => params[:happy_project_id]} %>


  <div class="form-group row mb-0">
    <div class="col-sm-9">
      <%= f.button :submit, class: "btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>
</div>

app/views/happy_project_members/edit.html.erb
<!-- <h2>Create Customer</h2> -->
<%= render 'edit_form' %>

app/views/happy_project_members/index.html.erb
<%= debug(params) %>
<%#= params[:project_id] %>
<div class="container">


  <h2>Happy Project Members</h2>
  
  <div class="customer-index-form">
     <%= simple_form_for :search, url: happy_project_members_path, method: "GET", html: { class: 'form-inline' } do |f| %>
     <label>
        <%= f.input :last_name, input_html: {value: ""} %>
     </label>

     <label>
        <%= f.submit "Search", class: "btn btn-primary" %>
     </label>
     <% end %>
  </div>

<div class="mb-4">
    <h6>Choose below project members</h6><br>
      <%= form_for(@happyProject) do |f| %>
        <div class="field">
          <%= hidden_field_tag "ht[happy_project_member_ids][]" %>
          <% @happyProject.happy_project_members.each do |member| %>
           
              <%= check_box_tag "ht[happy_project_member_ids][]", member.id, @happyProject.happy_project_member_ids.include?(member.id) %>
              <%= member.first_name %> <%= member.last_name %> <%= member.title%> <%= member.role%> <br>
            
          <% end %>
        </div>
          
             <br>
            <%= f.submit class: 'btn btn-primary' %>
        <% end %>
  </div>
  

  <%#= page_entries_info @happyProjectMembers %>
  <div class="table-responsive">          
  <table class="table">
    <thead>
      <tr>
        <th>Member ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @happyProjectMembers.each do |projectMember| %>
      <tr>
        <td><%= projectMember.id %></td>
        <td><%= projectMember.first_name %></td>
        <td><%= projectMember.last_name %></td>
        <td><%= projectMember.email %></td>
        <td><%= projectMember.phone_number %></td>
        <!--
        <%# if params[:project_id] %> 
          <td><%#=link_to "Add to Project - #{params[:project_name]}", happy_project_loadprocess_path(happy_project_id:  params[:project_id], id: projectMember.id) %></td>
          <td></td>
        <%# else %>
          -->
        <td><%= link_to 'Show', projectMember %></td>
        <td><%#= link_to 'Add Standard Task', happy_standard_tasks_path%></td>
        <td><%#= link_to 'Edit', edit_happy_customer_path(customer) %></td>
        <td><%#= link_to 'Destroy', customer, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
        <td><%#= link_to 'Quotes', happy_quotes_path(customer_id: customer.id, customer_name: customer.customer_name) %></td>
        <td><%#= link_to 'Orders', happy_orders_path %></td>
        <td><%#= link_to 'Vendors', happy_vendors_path %></td>
        <% end %>
      </tr>
      <%# end %>
    </tbody>
  </table>
  </div>
  <%#= paginate @happyProjectMembers, window: 2 %>
  <!-- 
  <h1>Happy Users</h1>
   <%# @happyUsers.each do |projectUsers| %>
      <td><%#= projectUsers.id %></td>
      <td><%#= projectUsers.email %> - </td>
       <%#= link_to 'Add', new_happy_project_member_path(user_id: projectUsers.id, user_email: projectUsers.email, happy_project_id: params[:project_id]) %><br>
      <br>
    <% #end%> 
    -->
<% if @happyVendorMembers %>
  <% @happyVendorMembers.each do |vendorMember| %>
        <td><%= vendorMember.first_name %></td>
        <td><%= vendorMember.last_name %> - </td>
  <% end %>
<% end %>


  <% if @happyProjectVendors.exists? %>  
    <h1>Vendors</h1>
    <% @happyProjectVendors.each do |projectVendor| %>
        <% @happyVendorMembers.each do |vendorMember| %>
          <td><%= projectVendor.happy_vendor_id %></td>
          <td><%= projectVendor.vendor_name %> - </td>
          <% if projectVendor.happy_vendor_id = vendorMember.happy_vendor_id %>
             <%#= link_to 'Add big boy', happy_project_member_path(happy_vendor_id: projectVendor.happy_vendor_id, vendor_name: projectVendor.vendor_name, happy_project_id: params[:happy_project_id]) %><br>
             <%= link_to 'View/Add Team Members', happy_project_team_path(id: '40', happy_project_id: params[:happy_project_id] ), class: 'btn btn-light' %>
             <% break %>
          <% else %>
            <%= link_to 'Add', new_happy_project_member_path(happy_vendor_id: projectVendor.happy_vendor_id, vendor_name: projectVendor.vendor_name, happy_project_id: params[:happy_project_id]) %><br>
          <br>
           <% end %>
        <% end %>
    <% end%>
   <% end %>
   <% if @happyProjectCustomer.exists? %> 
    <h1>Customers</h1>
   <% @happyProjectCustomer.each do |projectCustomer| %>
      <td><%= projectCustomer.id %></td>
      <td><%= projectCustomer.customer_name %> - </td>
       <%= link_to 'Add', new_happy_project_member_path(customer_id: projectCustomer.id, customer_name: projectCustomer.customer_name, happy_project_id: params[:happy_project_id]) %><br>
      <br>
    <% end%>
  <% end %>
<%= link_to 'New Happy Team Member', new_happy_project_member_path %><br>
<%= link_to 'New Happy Vendor Member', new_happy_project_member_path %><br>
<%= link_to 'New Happy Customer Member', new_happy_project_member_path %>
</div>

app/views/happy_project_members/new.html.erb
<!-- <h2>Create Customer</h2> -->
<%= render 'new_form' %>

app/views/happy_project_members/show.html.erb
<div class="container">
  <!-- <%#= link_to 'Home', root_path %> -->
  <h2>Happy Standard Project Process - <%= @happyStandardProcess.process_name %></h2>
  <br>
  <div class="row">
    <div class="col-sm">
      <p>
      <%= @happyStandardProcess.description %><br>
      </p>
    </div>
  </div>


  <div class="mb-4">
    <h6>Select below tasks</h6><br>
      <%= form_for(@happyStandardProcess) do |f| %>
        <div class="field">
          <%= hidden_field_tag "hp[happy_standard_task_ids][]" %>
          <% HappyStandardTask.all.each do |task| %>
            <%= check_box_tag "hp[happy_standard_task_ids][]", task.id, @happyStandardProcess.happy_standard_task_ids.include?(task.id) %>
            <%= task.task_name %>
          <% end %>
          </div>
             <br>
            <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>

<%= link_to 'Back', {:action => 'index'} %>
</div>